"""selected column

Revision ID: 533c7020a8a1
Revises: f88000ed5ec5
Create Date: 2023-01-27 17:25:13.298554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533c7020a8a1'
down_revision = 'f88000ed5ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('selected')

    # ### end Alembic commands ###
